services:
  weather-app:
    image: biraneves/weather-app:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: weather-app
