FROM golang:1.24 AS build

ARG LDFLAGS

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o svc ./cmd/server/ 

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /app
COPY --from=build /app/svc .

ENTRYPOINT ["./svc"]